services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: rhsenso_site
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rhsenso_pgdata:/var/lib/postgresql/data
volumes:
  rhsenso_pgdata:
